name: Sergei
app:
  name: short-app
  replicas: 1
  components: frontend
  image: antonlarichev/short-app
  version: v1.4
  port: 80
  limits:
    memory: "128Mi"
    cpu: "100m"

env: test
value:
  requirements:
    limits:
      memory: "128Mi"
      cpu: "100m"

users:
- name: Sergei
  role: admin
- name: Vasya
  role: manager
# Sergei: admin

api:
  name: short-api
  replicas: 1
  components: backend
  image: antonlarichev/short-api
  version: v1.0
  port: 3000
  mountPath: /etc/test
  limits:
    memory: "500Mi"
    cpu: "200m"
  envs:
  - DATABASE_URL

network:
  host: ches.test

database:
  user: demo
  password: demo
  db: demo
  host: postgres-clusterip


postgres:
  name: postgres
  image: postgres
  version: 16.0
  components: postgres
  mountPath: /var/lib/postgresql/data
  port: 5432
  type: ClusterIP
  resources:
    requests:
      storage: 1Gi
  limits:
    memory: "500Mi"
    cpu: "300m"
  envs:
  - POSTGRES_DB
  - POSTGRES_USER
  - POSTGRES_PASSWORD


