apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.postgres.name }}-pvc"
spec:
  resources:
    requests:
      storage: {{ .Values.postgres.resources.requests.storage }}
  accessModes:
  - ReadWriteOnce
