apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.postgres.name }}-clusterip"
spec:
  type: {{ .Values.postgres.type }}
  ports:
  - port: {{ .Values.postgres.port }}
    protocol: TCP
  selector:
    components: {{ .Values.postgres.components }}
